[phases.setup]
nixPkgs = ["php82", "php82Extensions.composer", "nodejs", "npm"]

[phases.install]
cmds = [
    "chmod +x deploy.sh",
    "./deploy.sh"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
] 