[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300

[deploy.startCommand]
preDeploy = [
  "php artisan config:cache",
  "php artisan route:cache", 
  "php artisan view:cache",
  "php artisan migrate --force",
  "php artisan storage:link"
] 